#!/bin/bash
all_git=(
./lazy/LuaSnip/.git
./lazy/luvit-meta/.git
./lazy/indent-blankline.nvim/.git
./lazy/telescope.nvim/.git
./lazy/nvim-snippets/.git
./lazy/nvim-treesitter-textobjects/.git
./lazy/which-key.nvim/.git
./lazy/catppuccin/.git
./lazy/nvim-docs-view/.git
./lazy/dashboard-nvim/.git
./lazy/cmp-nvim-lsp/.git
./lazy/tokyonight.nvim/.git
./lazy/conform.nvim/.git
./lazy/grug-far.nvim/.git
./lazy/mini.ai/.git
./lazy/flash.nvim/.git
./lazy/nvim-cmp/.git
./lazy/cmp-emoji/.git
./lazy/friendly-snippets/.git
./lazy/bufferline.nvim/.git
./lazy/nvim-ts-autotag/.git
./lazy/mini.pairs/.git
./lazy/nvim-lspconfig/.git
./lazy/todo-comments.nvim/.git
./lazy/cmp-path/.git
./lazy/mason.nvim/.git
./lazy/nvim-lint/.git
./lazy/nvim-treesitter/.git
./lazy/plenary.nvim/.git
./lazy/lazydev.nvim/.git
./lazy/dressing.nvim/.git
./lazy/nvim-notify/.git
./lazy/telescope-fzf-native.nvim/.git
./lazy/trouble.nvim/.git
./lazy/nui.nvim/.git
./lazy/lazy.nvim/.git
./lazy/neo-tree.nvim/.git
./lazy/mason-lspconfig.nvim/.git
./lazy/gitsigns.nvim/.git
./lazy/ts-comments.nvim/.git
./lazy/lualine.nvim/.git
./lazy/LazyVim/.git
./lazy/noice.nvim/.git
./lazy/cmp-buffer/.git
./lazy/mini.icons/.git
./lazy/persistence.nvim/.git
./depends/LuaSnip/.git
./depends/fidget.nvim/.git
./depends/telescope.nvim/.git
./depends/vim-dadbod-completion/.git
./depends/nvim-dap-vscode-js/.git
./depends/http-client.nvim/.git
./depends/ccc.nvim/.git
./depends/neovim-easy-less/.git
./depends/which-key.nvim/.git
./depends/lsp_extra_dim/.git
./depends/toggleterm.nvim/.git
./depends/nvim-autopairs/.git
./depends/Comment.nvim/.git
./depends/nvim-dap-ui/.git
./depends/nvim-ufo/.git
./depends/cmp-nvim-lsp/.git
./depends/vim-python-pep8-indent/.git
./depends/nvim-dap-virtual-text/.git
./depends/nvim-lightbulb/.git
./depends/web-tools.nvim/.git
./depends/vim-dadbod/.git
./depends/nvim-web-devicons/.git
./depends/nvim-cmp/.git
./depends/nvim-nio/.git
./depends/friendly-snippets/.git
./depends/bufferline.nvim/.git
./depends/nvim-ts-autotag/.git
./depends/killer-queen/.git
./depends/nvim-picgo/.git
./depends/neodev.nvim/.git
./depends/nvim-ts-context-commentstring/.git
./depends/cmp-cmdline/.git
./depends/nvim-lspconfig/.git
./depends/todo-comments.nvim/.git
./depends/null-ls.nvim/.git
./depends/cmp-path/.git
./depends/nvim-tree.lua/.git
./depends/mason.nvim/.git
./depends/vim-illuminate/.git
./depends/cmp_luasnip/.git
./depends/nvim-spectre/.git
./depends/nvim-treesitter/.git
./depends/plenary.nvim/.git
./depends/vim-dadbod-ui/.git
./depends/statuscol.nvim/.git
./depends/cmp-tabnine/.git
./depends/telescope-fzf-native.nvim/.git
./depends/symbol-usage.nvim/.git
./depends/promise-async/.git
./depends/translate.nvim/.git
./depends/nvim-hlslens/.git
./depends/lazy.nvim/.git
./depends/nvim-toggler/.git
./depends/mason-lspconfig.nvim/.git
./depends/nvim-dap/.git
./depends/gitsigns.nvim/.git
./depends/lualine.nvim/.git
./depends/nvim-markdown-preview/.git
./depends/cmp-buffer/.git
./depends/mini.icons/.git
./depends/venn.nvim/.git
./depends/aerial.nvim/.git
)

for dd in ${all_git[@]};do
    (cd ${dd%%/.git} && (git status -s -uno && git rev-parse --show-toplevel) | sed 'N;s/\n/ /' | awk '{if(NF>1)  print $3,"=>",$2}')
done
